[package]
name = "mpm"
version = "0.2.0"
authors = ["Max Breitenfeldt <git@mxbr.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
glam = "0.20.5"
